title: "Discussion"
labels: ["Incidents Review Meeting"]
body:
  - type: markdown
    attributes:
      value: |
        ## Participants
  - type: textarea
    id: Participants
    attributes:      
      description: "List of Participants for the Review Meeting"
      label: Participants
      value: |
        Mandatory Attendees:
        1. @sais8
        2. @phillipharrison
        Other Possible Attendees:
        1. @abhilashnallabelli
        2. @mathivanan-nb
        3. @sujith475
        4. @AG-Vashisth
        5. @markbirbeck
        6. @h3nllp
        7. @sankarshell
  - type: markdown
    attributes:
      value: |        
        ## Agenda
  - type: textarea
    id: Agenda
    attributes:      
      description: "Agenda of the Meeting"
      label: Agenda
      value: |
        1. Closed BUT delayed incident closure
        2. Recurring incidents (which ideally would be classified as problems)
        3. Open incidents at the time of review, ensure the Priority of the incident is documented in the notes. If there are P1 or P2 open at the time of this meeting, they should be observed and reported on daily until closure.
        4. Impact of KPIs defined - i.e. system down time etc,
        5. Action items - what actions have been / are required to be taken - Eg: Raise a finding etc
  - type: markdown
    attributes:
      value: | 
        ## KPI
  - type: textarea
    id: KPI
    attributes:      
      description: "KPI"
      label: KPI
      value: |
        Details of how the KPIs are calculated are in #4663, in this comment. Details of the SLA threshold calculations are in this comment. The SLO threshold calculations are described in this comment.
        ![image](https://user-images.githubusercontent.com/97517965/213198522-1f75bf69-3da7-4626-a412-8cce483409f7.png)
  - type: markdown
    attributes:
      value: | 
        ## Discussion
  - type: textarea
    id: Discussion
    attributes:      
      description: "Discussion"
      label: Discussion
      value: |
        Please add the discussed points here.
  - type: markdown
    attributes:
      value: | 
        ## Issues
  - type: textarea
    id: Issues
    attributes:      
      description: "Issues"
      label: issues
      value: |    
        Please add the details of issues faced.
  - type: markdown
    attributes:
      value: | 
        ## Decisions
  - type: textarea
    id: Decisions
    attributes:      
      description: "Decisions"
      label: decisions
      value: |
        - Please add the details regarding the decisions taken.
  - type: markdown
    attributes:
      value: |  
        ## Action Items
  - type: textarea
    id: ActionItems
    attributes:      
      description: "Action Items"
      label: items
      value: |
        Please add the Action items
  - type: markdown
    attributes:
      value: | 
        ## Additional Notes
  - type: textarea
    id: notes
    attributes:      
      description: "Additional Notes"
      label: notes
      value: |
        Please add additional notes
  
