name: 'Task: Check Stuck PRs'

on:
  push:
    branches:
      - main

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              search: ':NivedhaRavikumar is:issue project:projects/2/views/1 state:open -label:stuck',
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["stuck"]
            })
