name: 'Task: Check Stuck PRs'

on:
  push:
    branches:
      - main

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:      
      issues: write
      pull-requests: write
      contents: read
    steps:
     
      - uses: lee-dohm/select-matching-issues@v1
        with:
          query: 'users:NivedhaRavikumar is:issue project:projects/2/views/1 state:open -label:stuck'
          token: ${{ github.token }}
          #search: 'users:NivedhaRavikumar is:issue project:projects/2/views/1 state:open -label:stuck'
      - uses: actions/stale@v4
        with:          
          days-before-close: -1
          days-before-stale: 0
          exempt-pr-labels: 'blocked :no_entry_sign:,help wanted :raised_hand:'
          stale-pr-label: stuck
          stale-pr-message: >-
            This PR is stuck, since it hasn't been touched for 3 days.
            
            If progress has been made then please add a comment and remove the `stuck` label.
            
            Otherwise this ticket should be discussed in the standup and resources allocated
            in order to keep it moving.
