# This is a basic workflow to help you get started with Actions


name: 'Task: Schedule a DSX User Access Report'

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    name: Create a ticket for DSX User Access Report
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue to track User Access weekly Report
        uses: actions/github-script@v5
        
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Weekly DSX User Access Report',
              body: "## Description \n\nWe have to send a report which has a list of all Active Norske and SEEL users to @sreeharsha at the end of every month. \n\nPlease follow [NORSKE and SEEL Active Users Month End Report](https://turbo-barnacle-04dc7c1a.pages.github.io/incidents/playbooks/reports-norske-and-seel-active-users-month-end-report.html) Playbook.\n\n## Ticket Checklist \n\n<details><summary>Checklist</summary>\n\n- [ ] add ticket to `DSX SRE board` \n- [ ] set the `Service Class` as `Fixed date` \n- [ ] set the `Work Item Type` as `Chore` \n- [ ] set the `Board` as `Live` \n- [ ] Milestone should be set as last week of the month, create if not exist (eg: 2022-09-30) \n\n</details>\n\n## :white_check_mark: Tasks \n\n- [ ] run the query given on attached playbook in azure PROD and copy paste the results in excel\n- [ ] share the excel with @sreeharsha\n\n## :checkered_flag: Acceptance Criteria\n\n- NORSKE and SEEL Active Users Month End Report is generated and shared with @sreeharsha.",                                        
            })                
      
        
