# This is a basic workflow to help you get started with Actions


name: 'Task: Schedule a DSX User Access Report'

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    name: Create a ticket for DSX User Access Report
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue to track User Access weekly Report
        uses: actions/github-script@v5
        
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Weekly DSX User Access Report',
              body: "## Description \n\nTo create DSX User Access Weekly Report \n\nPlease follow [Generate and Send weekly DSX All Users Access Report](https://turbo-barnacle-04dc7c1a.pages.github.io/incidents/playbooks/dsx-all-users-access-report.html) Playbook.\n\n## :white_check_mark: Ticket Checklist \n\n<details><summary>Ticket Checklist</summary>\n\n- [ ] add ticket to `DSX SRE board` \n- [ ] set the `Service Class` as `Fixed date` \n- [ ] set the `Work Item Type` as `Chore` \n- [ ] set the `Board` as `Live` \n- [ ] Milestone should be set as current week Friday date, create if not exist (eg: 2022-08-12) \n\n</details>\n\n## Tasks \n\n- [ ]run query in azure for data download 1 and copy paste details in excel\n- [ ]run query in azure for data download 2 and copy paste details in excel\n- [ ]do sanity check for atleast 3 users.\n- [ ]check all fomulas and counts.\n\n## :checkered_flag: Acceptance Criteria\n\n- Weekly DSX all User Access Report is generated and shared with POS.",                                        
            })                
      - name: "Add issue to Project board"
        if: github.event_name == 'push'
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1        
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          GITHUB_PROJECT_URL: https://github.com/users/NivedhaRavikumar/projects/2
          GITHUB_PROJECT_COLUMN_NAME: To do
        #uses: actions/add-to-project@main
        #with:
        #  project-url: https://github.com/users/NivedhaRavikumar/projects/2
        #  github-token: ${{ secrets.MY_PAT }}
        
